/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package percobaan.calculator;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

public class CalculatorTest {

    @Test
    public void testAddition() {
        Calculator calculator = new Calculator();

        // 10 pengujian
        assertEquals(5, calculator.add(2, 3));
        assertEquals(10, calculator.add(5, 5));
        assertEquals(-1, calculator.add(2, -3));
        assertEquals(0, calculator.add(0, 0));
        assertEquals(100, calculator.add(50, 50));
        assertEquals(-10, calculator.add(-5, -5));
        assertEquals(7, calculator.add(10, -3));
        assertEquals(20, calculator.add(10, 10));
        assertEquals(15, calculator.add(7, 8));
        assertEquals(3, calculator.add(0, 3));
    }
}
