/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package percobaan.calculator;

public class Calculator {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Calculator().getGreeting());
    }

    public int add(int num1, int num2) {
        return num1 + num2;
    }
}
